config/routes.rb
Rails.application.routes.draw do
  resources :songs do
  member do
    get "vote"
  end
end

  resources :categories

  resources :postcards

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :category
  belongs_to :postcard
  acts_as_votable 
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy, :vote]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @song.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :lyric, :views, :keywords, :uploader, :performer, :writer, :album, :views_month, :status, :filename, :category_id, :postcard_id)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for @song, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lyric, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :lyric, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :views, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :views, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :keywords, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :keywords, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :uploader, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :uploader, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :performer, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :performer, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :writer, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :writer, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :album, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :album, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :views_month, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :views_month, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :status, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :filename, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :filename, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  songs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/songs/edit.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Song %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/index.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => Song %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:lyric) %></th>
      <th><%= model_class.human_attribute_name(:views) %></th>
      <th><%= model_class.human_attribute_name(:keywords) %></th>
      <th><%= model_class.human_attribute_name(:uploader) %></th>
      <th><%= model_class.human_attribute_name(:performer) %></th>
      <th><%= model_class.human_attribute_name(:writer) %></th>
      <th><%= model_class.human_attribute_name(:album) %></th>
      <th><%= model_class.human_attribute_name(:views_month) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:filename) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.id %></td>
        <td><%= song.name %></td>
        <td><%= song.lyric %></td>
        <td><%= song.views %></td>
        <td><%= song.keywords %></td>
        <td><%= song.uploader %></td>
        <td><%= song.performer %></td>
        <td><%= song.writer %></td>
        <td><%= song.album %></td>
        <td><%= song.views_month %></td>
        <td><%= song.status %></td>
        <td><%= song.filename %></td>
        <td><%=l song.created_at, format: :long %></td>
        <td>
          <%= link_to song_path(song), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to song_path(song), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_song_path,
            :class => 'btn btn-primary' %>

app/views/songs/new.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Song %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/show.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => Song %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @song.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:lyric) %></dt>
      <dd><pre class="prettyprint"><%= @song.lyric %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:views) %></dt>
      <dd><pre class="prettyprint"><%= @song.views %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:keywords) %></dt>
      <dd><pre class="prettyprint"><%= @song.keywords %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:uploader) %></dt>
      <dd><pre class="prettyprint"><%= @song.uploader %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:performer) %></dt>
      <dd><pre class="prettyprint"><%= @song.performer %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:writer) %></dt>
      <dd><pre class="prettyprint"><%= @song.writer %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:album) %></dt>
      <dd><pre class="prettyprint"><%= @song.album %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:views_month) %></dt>
      <dd><pre class="prettyprint"><%= @song.views_month %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:status) %></dt>
      <dd><pre class="prettyprint"><%= @song.status %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:filename) %></dt>
      <dd><pre class="prettyprint"><%= @song.filename %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              songs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_song_path(@song), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              song_path(@song),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>