config/routes.rb
Rails.application.routes.draw do
  resources :songs do
  member do
    get "vote"
  end
end

  resources :categories

  resources :postcards

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/postcard.rb
class Postcard < ActiveRecord::Base
  has_one :song
end

app/controllers/postcards_controller.rb
class PostcardsController < ApplicationController
  before_action :set_postcard, only: [:show, :edit, :update, :destroy]

  # GET /postcards
  # GET /postcards.json
  def index
    @postcards = Postcard.all
  end

  # GET /postcards/1
  # GET /postcards/1.json
  def show
  end

  # GET /postcards/new
  def new
    @postcard = Postcard.new
  end

  # GET /postcards/1/edit
  def edit
  end

  # POST /postcards
  # POST /postcards.json
  def create
    @postcard = Postcard.new(postcard_params)

    respond_to do |format|
      if @postcard.save
        format.html { redirect_to @postcard, notice: 'Postcard was successfully created.' }
        format.json { render :show, status: :created, location: @postcard }
      else
        format.html { render :new }
        format.json { render json: @postcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postcards/1
  # PATCH/PUT /postcards/1.json
  def update
    respond_to do |format|
      if @postcard.update(postcard_params)
        format.html { redirect_to @postcard, notice: 'Postcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @postcard }
      else
        format.html { render :edit }
        format.json { render json: @postcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postcards/1
  # DELETE /postcards/1.json
  def destroy
    @postcard.destroy
    respond_to do |format|
      format.html { redirect_to postcards_url, notice: 'Postcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postcard
      @postcard = Postcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postcard_params
      params.require(:postcard).permit(:recipient_name, :recipient_email, :sender_name, :sender_email, :message, :image_url, :deliver_on, :status)
    end
end

app/helpers/postcards_helper.rb
module PostcardsHelper
end

app/views/postcards/_form.html.erb
<%= form_for @postcard, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :recipient_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :recipient_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :recipient_email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :recipient_email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sender_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :sender_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sender_email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :sender_email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :message, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :message, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image_url, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :image_url, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deliver_on, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :deliver_on, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :status, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  postcards_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/postcards/edit.html.erb
<%- model_class = Postcard -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Postcard %></h1>
</div>
<%= render :partial => 'form' %>

app/views/postcards/index.html.erb
<%- model_class = Postcard -%>
<div class="page-header">
  <h1><%=t '.title', :default => Postcard %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:recipient_name) %></th>
      <th><%= model_class.human_attribute_name(:recipient_email) %></th>
      <th><%= model_class.human_attribute_name(:sender_name) %></th>
      <th><%= model_class.human_attribute_name(:sender_email) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:image_url) %></th>
      <th><%= model_class.human_attribute_name(:deliver_on) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @postcards.each do |postcard| %>
      <tr>
        <td><%= postcard.id %></td>
        <td><%= postcard.recipient_name %></td>
        <td><%= postcard.recipient_email %></td>
        <td><%= postcard.sender_name %></td>
        <td><%= postcard.sender_email %></td>
        <td><%= postcard.message %></td>
        <td><%= postcard.image_url %></td>
        <td><%= postcard.deliver_on %></td>
        <td><%= postcard.status %></td>
        <td><%=l postcard.created_at, format: :long %></td>
        <td>
          <%= link_to postcard_path(postcard), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to postcard_path(postcard), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_postcard_path,
            :class => 'btn btn-primary' %>

app/views/postcards/new.html.erb
<%- model_class = Postcard -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Postcard %></h1>
</div>
<%= render :partial => 'form' %>

app/views/postcards/show.html.erb
<%- model_class = Postcard -%>
<div class="page-header">
  <h1><%=t '.title', :default => Postcard %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:recipient_name) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.recipient_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:recipient_email) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.recipient_email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sender_name) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.sender_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sender_email) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.sender_email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:message) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.message %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:image_url) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.image_url %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:deliver_on) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.deliver_on %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:status) %></dt>
      <dd><pre class="prettyprint"><%= @postcard.status %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              postcards_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_postcard_path(@postcard), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              postcard_path(@postcard),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>